---
label: Project
hide_body: false
fields:
- type: file
  name: thumbnail
  label: Thumbnail
  description: This will only show up on the front page
- type: text
  name: title
  label: Title
  config:
    required: true
- type: textarea
  name: excerpt
  label: Excerpt
  description: Short snippet that will show outside of the actual post
- type: datetime
  name: date
  label: Date
  config:
    required: true
    date_format: YYYY-MM-DD
    time_format: ''
    export_format: YYYY-MM-DD
    display_utc: true
  default: now
  hidden: true
- type: tag_list
  name: categories
  label: Categories
- type: color
  name: project_bg_color
  config:
    color_format: Hex
  label: Background color
- type: color
  name: project_fg_color
  config:
    color_format: Hex
  label: Foreground color
  type: select
  name: author
  config:
    source:
      type: simple
      section: authors
      file: data/authors/nichlas-w-andersen.json
    required: true
    options:
    - Laney D. Fowler'
    - Victor A. Solis
  label: Author
  default: Laney D. Fowler
pages:

